### ISSUE TITLE
Posting Failed, TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by pav-elis** [sumcumo/cypress-testrail-reporter#8]
Hello
I have a problem:
When sending results to the testrail using this reporter, I got this error:
```
Posting Failed [
  TypeError: Cannot read property 'data' of undefined
      at onError (/home/pigeon/Документы/r5-click-aqa/node_modules/@sum.cumo/cypress-testrail-reporter/dist/reporter/index.js:80:36)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
]
```
This error first occured on 20.09(before this date everything worked correcly) and then every pipeline failed with this error message.

What I already checked:
1. Reproduced it locally, same error occured.
2. Re-tried with the previously created reports - same error occured even for reports that posted succesfully on 17.09 .
3. Made a little investigation and found that testrail had an [update](https://blog.gurock.com/announcing-testrail-7-2/) on 18.09 and I'm suspicious that this update was the reason(probably some API request/response structure chenged or some kind of that)

Can someone check this problem ASAP, please?

P.S.: here is the screenshots with the starting lines and ending lines for the `npx cypress-testrail-reporter --reportFilename output.json --name LocalTest` command log(local tests):
![image](https://user-images.githubusercontent.com/73487929/134930450-f14670ad-bb29-4838-b1b6-4e1ef98fd712.png)
![image](https://user-images.githubusercontent.com/73487929/134930507-ab09a032-22b2-4098-9329-23bd0582b00e.png)

**Comment by ma-jahn** [comment]
Hi @pavel-R5 

thank you for creating an issue.
One quick question. Which version of our `cypress-testrail-reporter` are you currently using?
We've released v1.5.0 on 19th of July to work with the Testrail API changes.

If you're running an older version, could you please try to update and try again?
Thank you!

**Comment by pav-elis** [comment]
Hmmm, that is weird, I had this in my package.json `"@sum.cumo/cypress-testrail-reporter": "^1.3.0"`, and according to NPM docs that should "update the package to all future minor/patch versions, without incrementing the major version".
I just put the latest version of the package there, and it seems like everything is working now both locally and in CI/CD, but why did it failed only last week...
Well that is probably some kind of missguidance in documentation for NPM plus internal changes in Testrail API flow that created this problem.
Thank you, @ma-jahn !

**Comment by ma-jahn** [comment]
Thanks for the quick check and feedback. Very happy that it could be resolved that quickly :-)
I'll close this issue but feel free to create new ones if you have question or feature requests :v:
